CREATE TABLE BRANCH(BNAME VARCHAR(20) PRIMARY KEY, BCITY VARCHAR(20), ASSETS FLOAT(11));

CREATE TABLE ACCOUNT(ACCNO INT(11) PRIMARY KEY,BNAME VARCHAR(11),BALANCE FLOAT, 
						FOREIGN KEY(BNAME) REFERENCES BRANCH(BNAME) ON DELETE CASCADE);

CREATE TABLE CUSTOMER(CNAME VARCHAR(11) PRIMARY KEY,CSTREET VARCHAR(11),CCITY VARCHAR(11));

CREATE TABLE DEPOSITOR(CNAME VARCHAR(11), ACCNO INT(11), PRIMARY KEY(CNAME,ACCNO) ,
						FOREIGN KEY(CNAME) REFERENCES CUSTOMER(CNAME) ON DELETE CASCADE, 
						FOREIGN KEY(ACCNO) REFERENCES ACCOUNT(ACCNO) ON DELETE CASCADE);

CREATE TABLE LOAN(LOANNO INT(11) PRIMARY KEY,BNAME VARCHAR(11), AMOUNT FLOAT, 
						FOREIGN KEY(BNAME) REFERENCES BRANCH(BNAME) ON DELETE CASCADE);

CREATE TABLE BORROWER(CNAME VARCHAR(11), LOANNO INT(11),PRIMARY KEY(CNAME,LOANNO), 
						FOREIGN KEY(LOANNO) REFERENCES LOAN(LOANNO) ON DELETE CASCADE, 
						FOREIGN KEY(CNAME) REFERENCES CUSTOMER(CNAME) ON DELETE CASCADE);


/*
iii) Find all the customers who have at least two accounts at the Main branch.
*/

SELECT D.CNAME 
	FROM DEPOSITOR D,
		ACCOUNT A 
	WHERE A.BNAME='PESSE' 
	AND A.ACCNO=D.ACCNO 
		GROUP BY D.CNAME 
		HAVING COUNT(*)>=2;


/*
iv) Find all the customers who have an account at all the
branches located in a specific city.
*/

SELECT D.CNAME 
	FROM ACCOUNT A,
		DEPOSITOR D,
		BRANCH B 
	WHERE D.ACCNO=A.ACCNO 
	AND A.BNAME=B.BNAME 
	AND B.BCITY='BANGALORE' 
		GROUP BY D.CNAME 
		HAVING COUNT(DISTINCT B.BNAME)=
			(SELECT COUNT(DISTINCT B.BNAME) 
				FROM BRANCH B 
				WHERE B.BCITY='BANGALORE');

/*
v) Demonstrate how you delete all account tuples at every
branch located in a specific city.
*/

DELETE FROM ACCOUNT 
	WHERE BNAME IN 
		(SELECT B.BNAME 
			FROM BRANCH B 
			WHERE B.BCITY='BANGALORE'); 